// One render function per email purpose, each returning its own subject + purpose-specific
// body — sharing only the chrome (brand header/footer) via wrapEmail. Kept as plain
// functions (not an Injectable) since rendering has no dependencies: AuthService and
// NotificationService import these directly, same as they'd build a string inline before.
const BRAND_COLOR = '#FF3366';
const BRAND_TINT = '#FFF6F8';
const BRAND_TINT_BORDER = '#FFD8E1';
const TEXT_PRIMARY = '#1A1A1A';
const TEXT_SECONDARY = '#4B4B52';
const TEXT_MUTED = '#8A8A8E';
const TEXT_FAINT = '#ACACB2';
const BORDER_LIGHT = '#EFEFF2';
const SUPPORT_EMAIL = 'support@eventrix.app';
const COMPANY_NAME = 'Eventrix';
// Custom URL scheme (Frontend/app.config.js's `scheme`) — a real deep link, not just
// "open the app" text. Not a universal/app link (no https:// fallback to a web page if
// the app isn't installed), which would additionally need a hosted domain +
// apple-app-site-association/assetlinks.json + App Store Connect/Play Console
// configuration that doesn't exist yet — see Frontend/src/navigation/linking.ts.
const APP_SCHEME = 'eventrix';

export interface RenderedEmail {
  subject: string;
  html: string;
}

// Every render* function below interpolates values that ultimately trace back to
// user/organizer/admin-entered text (display names, event titles, rejection reasons) —
// escape before interpolating so a display name like `<img src=x onerror=...>` can't
// inject markup into an email that otherwise looks like it's really from Eventrix.
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Subject lines are plain mail headers, not HTML — the risk there isn't markup injection,
// it's header injection (a title containing a raw CR/LF could, on a naive transport, forge
// extra headers like a Bcc). Strip control characters and cap length so a subject built from
// user-entered text (event titles, follower names) can never smuggle either.
function subjectSafe(value: string, maxLen = 60): string {
  const stripped = value.replace(/[\r\n]+/g, ' ').trim();
  return stripped.length > maxLen ? `${stripped.slice(0, maxLen - 1)}…` : stripped;
}

// Highlighted box for a one-time code (password reset / email verification).
function codeBox(code: string): string {
  return `
    <div style="margin:20px 0;padding:20px;background-color:${BRAND_TINT};border:1px solid ${BRAND_TINT_BORDER};border-radius:12px;text-align:center;">
      <span style="font-size:30px;font-weight:800;letter-spacing:8px;color:${BRAND_COLOR};font-family:'SF Mono',Consolas,Menlo,monospace;">${code}</span>
    </div>
  `;
}

// Labeled callout for supplementary detail (a cancellation/rejection reason, a booking
// reference, a status) — visually distinct from body copy so it reads as data, not prose.
function calloutBox(label: string, value: string): string {
  return `
    <div style="margin:16px 0;padding:14px 16px;background-color:#F7F7FA;border-left:3px solid ${BRAND_COLOR};border-radius:6px;">
      <p style="margin:0;font-size:12px;font-weight:600;color:${TEXT_MUTED};text-transform:uppercase;letter-spacing:0.5px;">${label}</p>
      <p style="margin:4px 0 0;font-size:14px;color:${TEXT_PRIMARY};">${value}</p>
    </div>
  `;
}

// Builds an eventrix://... deep link. path segments are IDs (UUIDs) generated by our own
// backend, never user-entered text, so no escaping concern beyond the encodeURIComponent
// already applied at each call site for defense in depth.
function appLink(path: string): string {
  return `${APP_SCHEME}://${path}`;
}

// Real tappable button pointing at a deep link — used only where a template actually has
// an id to link to (see each render* function below); falls back to plain "open the app"
// body copy where it doesn't (e.g. organizer verification emails have no screen of their
// own to deep-link into). label is always a static string we wrote, not user input.
function ctaButton(label: string, url: string): string {
  return `
    <div style="margin:20px 0;text-align:center;">
      <a href="${url}" style="display:inline-block;padding:12px 28px;background-color:${BRAND_COLOR};color:#FFFFFF;text-decoration:none;border-radius:999px;font-weight:700;font-size:14px;">${label}</a>
    </div>
  `;
}

function wrapEmail(heading: string, bodyHtml: string, preheader?: string): string {
  const year = new Date().getFullYear();
  return `
    <div style="background-color:#F4F4F7;padding:32px 16px;font-family:-apple-system,Helvetica,Arial,sans-serif;">
      ${preheader ? `<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${escapeHtml(preheader)}</div>` : ''}
      <div style="max-width:480px;margin:0 auto;background-color:#FFFFFF;border-radius:16px;overflow:hidden;border:1px solid ${BORDER_LIGHT};">
        <div style="padding:28px 32px;text-align:center;background-color:${BRAND_TINT};border-bottom:1px solid ${BRAND_TINT_BORDER};">
          <span style="font-size:22px;font-weight:800;color:${BRAND_COLOR};letter-spacing:0.3px;">${COMPANY_NAME}</span>
        </div>
        <div style="padding:32px;">
          <h1 style="margin:0 0 16px;font-size:19px;line-height:26px;color:${TEXT_PRIMARY};">${heading}</h1>
          <div style="font-size:15px;line-height:23px;color:${TEXT_SECONDARY};">
            ${bodyHtml}
          </div>
        </div>
        <div style="padding:20px 32px 28px;border-top:1px solid ${BORDER_LIGHT};">
          <p style="margin:0 0 8px;font-size:13px;color:${TEXT_MUTED};">
            Questions? Reach us anytime at <a href="mailto:${SUPPORT_EMAIL}" style="color:${BRAND_COLOR};text-decoration:none;">${SUPPORT_EMAIL}</a>.
          </p>
          <p style="margin:0 0 8px;font-size:12px;color:${TEXT_FAINT};">
            You're receiving this email because you have an ${COMPANY_NAME} account. This is an automated message — please don't reply directly to it.
          </p>
          <p style="margin:0;font-size:12px;color:${TEXT_FAINT};">&copy; ${year} ${COMPANY_NAME}. All rights reserved.</p>
        </div>
      </div>
    </div>
  `;
}

// --- Auth (auth.service.ts) ---

export function welcomeEmail(firstName: string): RenderedEmail {
  const safeName = escapeHtml(firstName || 'there');
  return {
    subject: `Welcome to ${COMPANY_NAME}, ${subjectSafe(firstName || 'there')}!`,
    html: wrapEmail(
      `Welcome to ${COMPANY_NAME}, ${safeName}! 🎉`,
      `
      <p>Your account is ready to go. Here's what you can do next:</p>
      <ul style="margin:0 0 16px;padding-left:20px;">
        <li style="margin-bottom:6px;">Browse and book events happening near you</li>
        <li style="margin-bottom:6px;">Follow organizers to hear about their next event first</li>
        <li>Create your own event and start selling tickets</li>
      </ul>
      <p>Open the ${COMPANY_NAME} app to get started.</p>
      <p>Have a question? Visit the <a href="${appLink('help-center')}" style="color:${BRAND_COLOR};">Help Center</a> in the app, or reach us directly at <a href="mailto:${SUPPORT_EMAIL}" style="color:${BRAND_COLOR};">${SUPPORT_EMAIL}</a>.</p>
      `,
      `Your ${COMPANY_NAME} account is ready — here's how to get started.`,
    ),
  };
}

export function passwordResetOtpEmail(otp: string, ttlMinutes: number): RenderedEmail {
  return {
    subject: `Your ${COMPANY_NAME} password reset code`,
    html: wrapEmail(
      'Reset your password',
      `
      <p>We received a request to reset your password. Enter this code in the app to continue:</p>
      ${codeBox(otp)}
      <p>This code expires in <strong>${ttlMinutes} minutes</strong>. Your password won't change until you enter it.</p>
      <p>If you didn't request this, you can safely ignore this email — no changes were made to your account.</p>
      `,
      `Your password reset code — expires in ${ttlMinutes} minutes.`,
    ),
  };
}

export function passwordChangedEmail(): RenderedEmail {
  return {
    subject: `Your ${COMPANY_NAME} password was changed`,
    html: wrapEmail(
      'Your password was changed',
      `
      <p>This confirms your ${COMPANY_NAME} account password was just changed.</p>
      <p>If this was you, no action is needed. If you didn't make this change, reset your password immediately from the login screen and contact us at <a href="mailto:${SUPPORT_EMAIL}" style="color:${BRAND_COLOR};">${SUPPORT_EMAIL}</a> right away.</p>
      `,
      'Your password was just changed — here\'s what to do if that wasn\'t you.',
    ),
  };
}

export function emailVerificationOtpEmail(otp: string, ttlMinutes: number): RenderedEmail {
  return {
    subject: `Verify your ${COMPANY_NAME} email address`,
    html: wrapEmail(
      'Verify your email address',
      `
      <p>Enter this code in the app to verify your email address:</p>
      ${codeBox(otp)}
      <p>This code expires in <strong>${ttlMinutes} minutes</strong>.</p>
      <p>If you didn't request this, you can safely ignore this email.</p>
      `,
      `Your email verification code — expires in ${ttlMinutes} minutes.`,
    ),
  };
}

export function passwordResetConfirmationEmail(): RenderedEmail {
  return {
    subject: `Your ${COMPANY_NAME} password was reset`,
    html: wrapEmail(
      'Your password was reset',
      `
      <p>Your ${COMPANY_NAME} password was just reset using the "Forgot password" flow.</p>
      <p>If this was you, no action is needed. If you didn't request this, your account may be compromised — contact us immediately at <a href="mailto:${SUPPORT_EMAIL}" style="color:${BRAND_COLOR};">${SUPPORT_EMAIL}</a>.</p>
      `,
      'Your password was just reset — here\'s what to do if that wasn\'t you.',
    ),
  };
}

// --- Notifications (notification.service.ts) ---

export function eventChangedEmail(eventId?: string): RenderedEmail {
  const link = eventId ? appLink(`event/${encodeURIComponent(eventId)}`) : undefined;
  return {
    subject: 'An event you\'re attending has been updated',
    html: wrapEmail(
      'An event you booked has changed',
      `
      <p>One of the events you're attending has been updated by its organizer — details like the time, venue, or description may have changed.</p>
      ${link ? ctaButton('View Event', link) : `<p>Open the ${COMPANY_NAME} app and check My Bookings to see exactly what changed.</p>`}
      `,
      'One of your upcoming events has been updated — check what changed.',
    ),
  };
}

export function waitlistPromotedEmail(enrollmentId?: string): RenderedEmail {
  const link = enrollmentId ? appLink(`booking/${encodeURIComponent(enrollmentId)}`) : undefined;
  return {
    subject: `You're in! A spot opened up`,
    html: wrapEmail(
      "You're off the waitlist!",
      `
      <p>Good news — a spot opened up and you've been moved off the waitlist. Your ticket is now confirmed.</p>
      ${link ? ctaButton('View Your Ticket', link) : `<p>Open the ${COMPANY_NAME} app and check My Bookings to view your ticket.</p>`}
      `,
      'A spot opened up — your ticket is now confirmed.',
    ),
  };
}

export function refundStatusEmail(status: string, enrollmentId?: string): RenderedEmail {
  const link = enrollmentId ? appLink(`booking/${encodeURIComponent(enrollmentId)}`) : undefined;
  if (status === 'requested') {
    return {
      subject: 'Refund request received',
      html: wrapEmail(
        'Refund request received',
        `
        <p>We've received your refund request and it's now being reviewed.</p>
        <p>You'll get another email as soon as there's an update — no action is needed from you right now.</p>
        `,
        'We\'ve received your refund request and it\'s under review.',
      ),
    };
  }
  const safeStatus = escapeHtml(status);
  return {
    subject: `Refund update: ${subjectSafe(status)}`,
    html: wrapEmail(
      'Refund status update',
      `
      <p>There's an update on your refund request.</p>
      ${calloutBox('Status', safeStatus)}
      ${link ? ctaButton('View Booking', link) : `<p>Open the ${COMPANY_NAME} app and check My Bookings for the full details.</p>`}
      `,
      `Your refund status is now "${status}".`,
    ),
  };
}

export function announcementEmail(title: string, eventId?: string): RenderedEmail {
  const safeTitle = escapeHtml(title);
  const link = eventId ? appLink(`event/${encodeURIComponent(eventId)}`) : undefined;
  return {
    subject: `New announcement: ${subjectSafe(title)}`,
    html: wrapEmail(
      'New announcement from an organizer you follow',
      `
      ${calloutBox('Announcement', safeTitle)}
      ${link ? ctaButton('View Event', link) : `<p>Open the ${COMPANY_NAME} app to read the full announcement and join the conversation.</p>`}
      `,
      `New announcement: ${title}`,
    ),
  };
}

export function organizerFollowedEmail(followerName: string): RenderedEmail {
  const safeName = escapeHtml(followerName);
  return {
    subject: `${subjectSafe(followerName)} started following you`,
    html: wrapEmail(
      'You have a new follower',
      `
      <p><strong>${safeName}</strong> started following you on ${COMPANY_NAME} and will be notified about your future events.</p>
      <p>Open the ${COMPANY_NAME} app to view your followers or manage your organizer profile.</p>
      `,
      `${followerName} started following you on ${COMPANY_NAME}.`,
    ),
  };
}

export function eventCancelledEmail(eventTitle: string, reason?: string, eventId?: string): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle);
  const reasonHtml = reason ? calloutBox('Reason', escapeHtml(reason)) : '';
  const link = eventId ? appLink(`event/${encodeURIComponent(eventId)}`) : undefined;
  return {
    subject: `Event cancelled: ${subjectSafe(eventTitle)}`,
    html: wrapEmail(
      'Event cancelled',
      `
      <p><strong>${safeTitle}</strong> has been cancelled by its organizer.</p>
      ${reasonHtml}
      <p>If you paid for this booking, open the app, go to My Bookings, and request a refund — most refunds are reviewed within a few days.</p>
      ${link ? ctaButton('View Event', link) : ''}
      `,
      `"${eventTitle}" has been cancelled.`,
    ),
  };
}

export function bookingConfirmedEmail(
  eventTitle: string,
  bookingReference: string,
  quantity: number,
  enrollmentId?: string,
  eventDate?: string,
  startTime?: string,
  venueName?: string,
  // True once a ticket-QR attachment has actually been embedded alongside this email
  // (see NotificationService.buildEmailAttachments) — controls whether the QR <img> tag
  // is rendered here, since referencing a cid: that isn't actually attached would just
  // show a broken image.
  hasQrAttachment?: boolean,
): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle);
  const safeReference = escapeHtml(bookingReference);
  const ticketWord = quantity === 1 ? 'ticket' : 'tickets';
  const link = enrollmentId ? appLink(`booking/${encodeURIComponent(enrollmentId)}`) : undefined;
  const detailsHtml = [
    eventDate ? calloutBox('Date', escapeHtml(eventDate)) : '',
    startTime ? calloutBox('Time', escapeHtml(startTime)) : '',
    venueName ? calloutBox('Location', escapeHtml(venueName)) : '',
  ].join('');
  const qrHtml = hasQrAttachment
    ? `<div style="margin:20px 0;text-align:center;"><img src="cid:ticket-qr" alt="Ticket QR code" width="180" height="180" style="border-radius:12px;" /></div>`
    : '';
  return {
    subject: `Booking confirmed: ${subjectSafe(eventTitle)}`,
    html: wrapEmail(
      'Booking confirmed 🎟️',
      `
      <p>You're confirmed for <strong>${safeTitle}</strong> (${quantity} ${ticketWord}).</p>
      ${calloutBox('Booking reference', safeReference)}
      ${detailsHtml}
      ${qrHtml}
      ${link ? ctaButton('View Your Ticket', link) : `<p>Open the ${COMPANY_NAME} app and go to My Bookings to view your ticket and QR code anytime.</p>`}
      `,
      `You're confirmed for ${eventTitle} — ${quantity} ${ticketWord}.`,
    ),
  };
}

// A money row for the invoice/payout tables below. `emphasis` renders the final total;
// `negative` renders a deduction with a minus sign, used on the organizer's payout summary.
function amountRow(label: string, amount: number, opts: { emphasis?: boolean; negative?: boolean } = {}): string {
  const weight = opts.emphasis ? '700' : '400';
  const color = opts.emphasis ? TEXT_PRIMARY : TEXT_SECONDARY;
  const size = opts.emphasis ? '16px' : '14px';
  const border = opts.emphasis ? `border-top:2px solid ${BORDER_LIGHT};` : `border-top:1px solid ${BORDER_LIGHT};`;
  const value = `${opts.negative ? '−' : ''}₹${Math.abs(amount).toFixed(2)}`;
  return `
    <tr>
      <td style="${border}padding:10px 0;font-size:${size};font-weight:${weight};color:${color};">${label}</td>
      <td style="${border}padding:10px 0;font-size:${size};font-weight:${weight};color:${color};text-align:right;white-space:nowrap;">${value}</td>
    </tr>
  `;
}

function amountTable(rows: string): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:16px 0;border-collapse:collapse;">${rows}</table>`;
}

export interface InvoiceEmailLine {
  label: string;
  amount: number;
}

// Tax receipt for a settled booking. Deliberately separate from bookingConfirmedEmail (which
// carries the ticket + QR): this one is the financial document a buyer forwards to an
// employer or accountant, and it should stand alone without the ticket attached.
//
// `lines` is built by the caller rather than assembled here, because WHICH fee lines a buyer
// may be shown depends on who actually paid them — under feePayer=ORGANIZER the buyer was
// charged only the ticket price, and itemising platform fees would claim charges they never
// incurred. See PaymentsService/InvoiceDetailScreen for the same rule on the app side.
export function invoiceEmail(
  invoiceNumber: string,
  eventTitle: string,
  lines: InvoiceEmailLine[],
  total: number,
  currencySymbolIsRupee: boolean,
  enrollmentId?: string,
  transactionId?: string,
): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle);
  const safeInvoice = escapeHtml(invoiceNumber);
  const link = enrollmentId ? appLink(`booking/${encodeURIComponent(enrollmentId)}`) : undefined;
  // Every template here renders ₹ directly; a non-INR event would misstate the currency, so
  // fall back to naming the amount without a symbol rather than printing the wrong one.
  const rows =
    lines.map((line) => amountRow(escapeHtml(line.label), line.amount)).join('') +
    amountRow('Total paid', total, { emphasis: true });
  return {
    subject: `Invoice ${subjectSafe(invoiceNumber, 40)} — ${subjectSafe(eventTitle, 40)}`,
    html: wrapEmail(
      'Your invoice 🧾',
      `
      <p>Here's the receipt for your booking of <strong>${safeTitle}</strong>.</p>
      ${calloutBox('Invoice number', safeInvoice)}
      ${currencySymbolIsRupee ? amountTable(rows) : `<p>Total paid: ${total.toFixed(2)}</p>`}
      ${transactionId ? calloutBox('Transaction reference', escapeHtml(transactionId)) : ''}
      ${link ? ctaButton('View Invoice', link) : ''}
      <p style="font-size:12px;color:${TEXT_FAINT};">This is a computer-generated invoice and does not require a signature.</p>
      `,
      `Invoice ${invoiceNumber} for ${eventTitle}.`,
    ),
  };
}

// Sent to the organizer once the T+3 sweep has settled an event's payout. States plainly
// that this records the payout, since the actual bank transfer is handled out of band.
export function payoutProcessedEmail(
  eventTitle: string,
  ticketCount: number,
  grossRevenue: number,
  platformFee: number,
  gatewayFee: number,
  payoutAmount: number,
): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle);
  const ticketWord = ticketCount === 1 ? 'ticket' : 'tickets';
  const rows =
    amountRow(`Gross from ${ticketCount} ${ticketWord}`, grossRevenue) +
    (platformFee > 0 ? amountRow('Platform fee', platformFee, { negative: true }) : '') +
    (gatewayFee > 0 ? amountRow('Payment processing fee', gatewayFee, { negative: true }) : '') +
    amountRow('Your payout', payoutAmount, { emphasis: true });
  return {
    subject: `Payout processed: ${subjectSafe(eventTitle)}`,
    html: wrapEmail(
      'Payout processed 💸',
      `
      <p>Your payout for <strong>${safeTitle}</strong> has been settled.</p>
      ${amountTable(rows)}
      <p>Funds are transferred to your registered bank account separately — if anything looks wrong, reply to this email before the transfer is made.</p>
      `,
      `Payout of ₹${payoutAmount.toFixed(2)} settled for ${eventTitle}.`,
    ),
  };
}

export function eventApprovedEmail(eventTitle: string, eventId?: string): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle);
  const link = eventId ? appLink(`event/${encodeURIComponent(eventId)}`) : undefined;
  return {
    subject: `Your event was approved: ${subjectSafe(eventTitle)}`,
    html: wrapEmail(
      "You're live! 🎉",
      `
      <p><strong>${safeTitle}</strong> has been approved and is now visible to everyone on ${COMPANY_NAME}.</p>
      ${link ? ctaButton('View Event', link) : `<p>Open the ${COMPANY_NAME} app to view your listing.</p>`}
      `,
      `"${eventTitle}" has been approved and is now live.`,
    ),
  };
}

export function eventRejectedEmail(eventTitle: string, reason: string, eventId?: string): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle);
  const reasonHtml = reason ? calloutBox('Reason', escapeHtml(reason)) : '';
  const link = eventId ? appLink(`event/${encodeURIComponent(eventId)}`) : undefined;
  return {
    subject: `Your event needs changes: ${subjectSafe(eventTitle)}`,
    html: wrapEmail(
      'Your event needs another look',
      `
      <p><strong>${safeTitle}</strong> wasn't approved this time.</p>
      ${reasonHtml}
      <p>Open the ${COMPANY_NAME} app, update the listing, and resubmit for review.</p>
      ${link ? ctaButton('View Event', link) : ''}
      `,
      `"${eventTitle}" needs changes before it can go live.`,
    ),
  };
}

export function organizerVerificationApprovedEmail(): RenderedEmail {
  return {
    subject: `You're verified! Start creating events`,
    html: wrapEmail(
      "You're verified! 🎉",
      `
      <p>Your organizer verification was approved — you can now create and publish events on ${COMPANY_NAME}.</p>
      <p>Open the ${COMPANY_NAME} app and tap "Create Event" to publish your first listing.</p>
      `,
      'Your organizer verification was approved — start creating events.',
    ),
  };
}

export function organizerVerificationRejectedEmail(reason: string): RenderedEmail {
  const reasonHtml = reason ? calloutBox('Reason', escapeHtml(reason)) : '';
  return {
    subject: 'Your organizer verification needs another look',
    html: wrapEmail(
      'Verification needs another look',
      `
      <p>Your organizer verification wasn't approved this time.</p>
      ${reasonHtml}
      <p>Open the ${COMPANY_NAME} app, update your details from your profile, and resubmit for review.</p>
      `,
      'Your organizer verification needs another look before you can publish events.',
    ),
  };
}

export function organizerVerificationSubmittedEmail(): RenderedEmail {
  return {
    subject: 'Your organizer verification was submitted',
    html: wrapEmail(
      'Documents submitted for review',
      `
      <p>We've received your organizer verification documents. An admin will review them — this usually takes 1-2 business days.</p>
      <p>You'll get another email as soon as a decision is made, and you can check the status anytime from your profile.</p>
      `,
      "We've received your organizer verification documents — here's what happens next.",
    ),
  };
}

export function organizerVerificationNewSubmissionEmail(applicantName: string, companyName: string): RenderedEmail {
  const safeName = escapeHtml(applicantName || 'An applicant');
  const safeCompany = escapeHtml(companyName || 'their business');
  return {
    subject: 'New organizer verification submitted',
    html: wrapEmail(
      'New verification to review',
      `
      <p>${safeName} submitted organizer verification documents for <strong>${safeCompany}</strong>.</p>
      <p>Open the admin dashboard to review their documents and approve or reject the submission.</p>
      `,
      `${safeName} submitted organizer verification documents for review.`,
    ),
  };
}

// --- Admin review queue (NotificationService.enqueueForAdmins) ---
// All three go to admins, not to the user who triggered them, and deliberately carry no
// deep link: the review screens they point at live in the web dashboard, not the app.

export function eventPendingApprovalEmail(eventTitle: string, organizerName: string): RenderedEmail {
  const safeTitle = escapeHtml(eventTitle || 'An event');
  const safeOrganizer = escapeHtml(organizerName || 'An organizer');
  return {
    subject: subjectSafe(`Event awaiting approval: ${eventTitle || 'An event'}`),
    html: wrapEmail(
      'Event awaiting approval',
      `
      <p>${safeOrganizer} submitted <strong>${safeTitle}</strong> for review.</p>
      <p>Open the admin dashboard to review the event and approve or reject it.</p>
      `,
      `${safeOrganizer} submitted an event for review.`,
    ),
  };
}

export function refundRequestedEmail(requesterName: string, eventTitle: string, amount: number): RenderedEmail {
  const safeName = escapeHtml(requesterName || 'A participant');
  const safeTitle = escapeHtml(eventTitle || 'an event');
  return {
    subject: 'New refund request to review',
    html: wrapEmail(
      'Refund request to review',
      `
      <p>${safeName} requested a refund for <strong>${safeTitle}</strong>.</p>
      ${calloutBox('Amount', `&#8377;${amount.toFixed(2)}`)}
      <p>Open the admin dashboard to approve or reject the request.</p>
      `,
      `${safeName} requested a refund.`,
    ),
  };
}

export function userReportedEmail(reporterName: string, targetType: string, reason: string): RenderedEmail {
  const safeName = escapeHtml(reporterName || 'Someone');
  const safeTarget = escapeHtml((targetType || 'user').replace(/_/g, ' '));
  const safeReason = escapeHtml(reason || '');
  return {
    subject: subjectSafe(`New ${targetType || 'user'} report filed`),
    html: wrapEmail(
      'New report to review',
      `
      <p>${safeName} reported a ${safeTarget}.</p>
      ${safeReason ? calloutBox('Reason', safeReason) : ''}
      <p>Open the admin dashboard to review the report and take action or dismiss it.</p>
      `,
      `${safeName} reported a ${safeTarget}.`,
    ),
  };
}

// Self-service "download my data" (Settings → Data & Privacy). jsonPretty is our own
// JSON.stringify output, not user-entered text, but escaped anyway on the same
// defense-in-depth basis as everything else in this file — cheap, and it's the values
// nested inside (names, bios) that really are user-controlled.
export function dataExportEmail(jsonPretty: string): RenderedEmail {
  return {
    subject: `Your ${COMPANY_NAME} data export`,
    html: wrapEmail(
      'Your data export is ready',
      `
      <p>As requested, here is a copy of your ${COMPANY_NAME} account data.</p>
      <pre style="margin:16px 0;padding:16px;background-color:#F7F7FA;border-radius:8px;font-size:12px;line-height:18px;color:${TEXT_PRIMARY};white-space:pre-wrap;word-break:break-word;font-family:'SF Mono',Consolas,Menlo,monospace;">${escapeHtml(jsonPretty)}</pre>
      <p>If you didn't request this, please contact us immediately at <a href="mailto:${SUPPORT_EMAIL}" style="color:${BRAND_COLOR};">${SUPPORT_EMAIL}</a>.</p>
      `,
      `Your requested ${COMPANY_NAME} data export.`,
    ),
  };
}
