import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPushTokenToUser1784898046405 implements MigrationInterface {
    name = 'AddPushTokenToUser1784898046405'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ticket_types" DROP CONSTRAINT "FK_ticket_types_event"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "FK_event_bookings_payout"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "FK_event_bookings_ticket_type"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "event_bookings_event_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "event_bookings_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "event_media" DROP CONSTRAINT "FK_event_media_event"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "events_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "events_organizer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "fk_events_approved_by"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "fk_events_rejected_by"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "fk_events_updated_by"`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP CONSTRAINT "organizers_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_enrollment"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_commissions_payment"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_refunds_enrollment"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_waitlist_entries_event"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_waitlist_entries_ticket_type"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_waitlist_entries_user"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_event"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_organizer"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_favorites_event"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_favorites_user"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_follows_organizer"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_follows_user"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_event"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_user"`);
        await queryRunner.query(`ALTER TABLE "event_schedule_items" DROP CONSTRAINT "FK_event_schedule_items_event"`);
        await queryRunner.query(`ALTER TABLE "event_announcements" DROP CONSTRAINT "FK_event_announcements_event"`);
        await queryRunner.query(`ALTER TABLE "event_announcements" DROP CONSTRAINT "FK_event_announcements_user"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "event_reviews_event_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "event_reviews_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP CONSTRAINT "shorts_creator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP CONSTRAINT "shorts_event_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_interests" DROP CONSTRAINT "FK_user_interests_category"`);
        await queryRunner.query(`ALTER TABLE "user_interests" DROP CONSTRAINT "FK_user_interests_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ticket_types_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_bookings_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_bookings_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_bookings_reference"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_event_bookings_ticket_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_bookings_payout_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_media_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_organizer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_featured"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_events_event_date_start_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_events_approval_status_deleted_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_events_category_id_event_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_events_title"`);
        await queryRunner.query(`DROP INDEX "public"."idx_organizers_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payments_gateway_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_enrollment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refunds_enrollment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refunds_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_waitlist_entries_tt_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_target"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_actor_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_organizer_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_jobs_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_password_reset_otps_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_email_verification_otps_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_favorites_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_follows_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_follows_organizer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_messages_event_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_schedule_items_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_announcements_event_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_reviews_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_reviews_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_reviews_event"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shorts_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shorts_creator_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shorts_event_id"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "CHK_events_end_date_after_start"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "event_reviews_rating_check"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "UQ_waitlist_entries_user_ticket_type"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "UQ_favorites_user_event"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_follows_user_organizer"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "event_reviews_user_id_event_id_key"`);
        await queryRunner.query(`ALTER TABLE "event_announcements" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "review_title"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "review_text"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "helpful_count"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "creator_id"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "video_url"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "duration_seconds"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "push_token" character varying`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "text" text`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "uploader_user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "media_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "caption" text`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "moderation_status" character varying(20) NOT NULL DEFAULT 'under_review'`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "flag_reason" text`);
        await queryRunner.query(`ALTER TABLE "event_categories" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_categories" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "total_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "total_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "booking_status"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "booking_status" character varying NOT NULL DEFAULT 'confirmed'`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "payment_status"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "payment_status" character varying DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "payment_method" character varying`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "event_bookings_booking_reference_key"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "booking_reference"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "booking_reference" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "UQ_3c8ed28a882f2b9a5caef4038b4" UNIQUE ("ticket_code")`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "ticket_code" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "booking_date" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "approval_status"`);
        await queryRunner.query(`CREATE TYPE "public"."events_approval_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "events" ADD "approval_status" "public"."events_approval_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_by_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "featured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('upcoming', 'ongoing', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "events" ADD "status" "public"."events_status_enum" NOT NULL DEFAULT 'upcoming'`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "approval_method" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_description"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_description" character varying`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_website"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_website" character varying`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_logo_url"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_logo_url" character varying`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_picture_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_picture_url" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bio" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "latitude" TYPE numeric(11,8)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "roles" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "roles" SET DEFAULT '["user"]'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "notification_prefs" SET DEFAULT '{"eventReminders":true,"nearbyEvents":true,"reelsAndCommunity":true,"specialOffers":true}'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "UQ_f5eea852caade6015a86c6cc82a" UNIQUE ("gateway_event_id")`);
        await queryRunner.query(`ALTER TABLE "refunds" ALTER COLUMN "requested_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "rating" smallint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "view_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_9dfa62b35548ea1e0b7e4675b2" ON "ticket_types" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_27fcf8353977273f67a62a4172" ON "event_bookings" ("event_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_16a84aef47c794ac3d01f39830" ON "event_media" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bab6cf3a1e33e6790e9b9bd7d1" ON "events" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_0410389b8d9e26a76bc4df7050" ON "events" ("category_id", "event_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_019da5caef36b1a1af22063905" ON "events" ("approval_status", "deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1c97e41edad2dd3e2c225f458a" ON "events" ("event_date", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a390dc6ab65942f1ab577b7b6" ON "payments" ("enrollment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_90c78d3c32a3346772edf34e73" ON "refunds" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f6dd1048ea0bdfe60c4a3300d" ON "refunds" ("enrollment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23a4e63a095ea45c880ee03d80" ON "waitlist_entries" ("ticket_type_id", "status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a85d553dbb4006bd350ab6f88" ON "audit_logs" ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a358c00ae08bdea24880372d7a" ON "audit_logs" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_656ab973b96252a340fca6dc33" ON "payouts" ("organizer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_fefceb5358f13649852bcddee4" ON "payouts" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_033a1fdb4f9af609010a4a3ba9" ON "notification_jobs" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ce12a460128d0abb45de6d9cb" ON "password_reset_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c210d0e51865d0a90546373db" ON "email_verification_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_934b1fb8522f51ab5b85da5d43" ON "chat_messages" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_52d89390506ed998a56a73c04c" ON "chat_messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbd9d981fd6608f76099c162a4" ON "event_schedule_items" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2df1df8ffbc22c818c2ffd6af8" ON "event_announcements" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ac846a09922d70bea98c9b7e2" ON "event_reviews" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ed421885e47e81f23930974f9" ON "shorts" ("moderation_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb0511a8fabd1a2ac9912f7a9a" ON "user_interests" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d291265e63ae6c1a50de31682" ON "user_interests" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "UQ_27fcf8353977273f67a62a41728" UNIQUE ("user_id", "event_id")`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "UQ_33bf2a75397e524c2ba04d99a65" UNIQUE ("user_id", "ticket_type_id")`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "UQ_a988b004ac89d43755511fdf88f" UNIQUE ("user_id", "event_id")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_bb11f650c47c2183fd1d1fa0e04" UNIQUE ("user_id", "organizer_id")`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "UQ_b1decc491b2adb75c8aded75b13" UNIQUE ("event_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ADD CONSTRAINT "FK_9dfa62b35548ea1e0b7e4675b20" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "FK_84db7813e10d21b2a417c62ad75" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "FK_82620d9562ee965366b465bcf1c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "FK_5b809dcb91587b57423cdd8f01b" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_16a84aef47c794ac3d01f39830c" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_643188b30e049632f80367be4e1" FOREIGN KEY ("category_id") REFERENCES "event_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_14c9ce53a2c2a1c781b8390123e" FOREIGN KEY ("organizer_id") REFERENCES "organizers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD CONSTRAINT "FK_72940a919e9a6c7ec65a330349b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1a390dc6ab65942f1ab577b7b65" FOREIGN KEY ("enrollment_id") REFERENCES "event_bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_b57b1306fdd71690cd88300b7bb" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_6f6dd1048ea0bdfe60c4a3300dc" FOREIGN KEY ("enrollment_id") REFERENCES "event_bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_b6dd23d94ea644df6ad968b2735" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_5d55152187b936078581a014e8f" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_accc0d911773551b2eed1a2ed72" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_84194eaba2a5d87150491df69a9" FOREIGN KEY ("organizer_id") REFERENCES "organizers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_fefceb5358f13649852bcddee42" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_b4bd4b6a0d2dca5cfa98905bb81" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_941d172275662c2b9d8b9f4270c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_17b67878bea45a0e2b9bcf5c1ef" FOREIGN KEY ("organizer_id") REFERENCES "organizers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_934b1fb8522f51ab5b85da5d438" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_5588b6cea298cedec7063c0d33e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_schedule_items" ADD CONSTRAINT "FK_cbd9d981fd6608f76099c162a46" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_announcements" ADD CONSTRAINT "FK_2df1df8ffbc22c818c2ffd6af81" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_announcements" ADD CONSTRAINT "FK_83b037637ed291337c3f05ebcbc" FOREIGN KEY ("posted_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "FK_2ac846a09922d70bea98c9b7e21" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "FK_d07a846551ad1f7de1ef11e0288" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD CONSTRAINT "FK_af164b0336739129bac4dc21e3f" FOREIGN KEY ("uploader_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD CONSTRAINT "FK_4f407a325ddfd73443cdceeab55" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_interests" ADD CONSTRAINT "FK_cb0511a8fabd1a2ac9912f7a9aa" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_interests" ADD CONSTRAINT "FK_1d291265e63ae6c1a50de31682e" FOREIGN KEY ("category_id") REFERENCES "event_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_interests" DROP CONSTRAINT "FK_1d291265e63ae6c1a50de31682e"`);
        await queryRunner.query(`ALTER TABLE "user_interests" DROP CONSTRAINT "FK_cb0511a8fabd1a2ac9912f7a9aa"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP CONSTRAINT "FK_4f407a325ddfd73443cdceeab55"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP CONSTRAINT "FK_af164b0336739129bac4dc21e3f"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "FK_d07a846551ad1f7de1ef11e0288"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "FK_2ac846a09922d70bea98c9b7e21"`);
        await queryRunner.query(`ALTER TABLE "event_announcements" DROP CONSTRAINT "FK_83b037637ed291337c3f05ebcbc"`);
        await queryRunner.query(`ALTER TABLE "event_announcements" DROP CONSTRAINT "FK_2df1df8ffbc22c818c2ffd6af81"`);
        await queryRunner.query(`ALTER TABLE "event_schedule_items" DROP CONSTRAINT "FK_cbd9d981fd6608f76099c162a46"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_5588b6cea298cedec7063c0d33e"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_934b1fb8522f51ab5b85da5d438"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_17b67878bea45a0e2b9bcf5c1ef"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_941d172275662c2b9d8b9f4270c"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_b4bd4b6a0d2dca5cfa98905bb81"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_fefceb5358f13649852bcddee42"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_84194eaba2a5d87150491df69a9"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_accc0d911773551b2eed1a2ed72"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_5d55152187b936078581a014e8f"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_b6dd23d94ea644df6ad968b2735"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_6f6dd1048ea0bdfe60c4a3300dc"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_b57b1306fdd71690cd88300b7bb"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1a390dc6ab65942f1ab577b7b65"`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP CONSTRAINT "FK_72940a919e9a6c7ec65a330349b"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_14c9ce53a2c2a1c781b8390123e"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_643188b30e049632f80367be4e1"`);
        await queryRunner.query(`ALTER TABLE "event_media" DROP CONSTRAINT "FK_16a84aef47c794ac3d01f39830c"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "FK_5b809dcb91587b57423cdd8f01b"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "FK_82620d9562ee965366b465bcf1c"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "FK_84db7813e10d21b2a417c62ad75"`);
        await queryRunner.query(`ALTER TABLE "ticket_types" DROP CONSTRAINT "FK_9dfa62b35548ea1e0b7e4675b20"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP CONSTRAINT "UQ_b1decc491b2adb75c8aded75b13"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_bb11f650c47c2183fd1d1fa0e04"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "UQ_a988b004ac89d43755511fdf88f"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "UQ_33bf2a75397e524c2ba04d99a65"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "UQ_27fcf8353977273f67a62a41728"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d291265e63ae6c1a50de31682"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb0511a8fabd1a2ac9912f7a9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ed421885e47e81f23930974f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ac846a09922d70bea98c9b7e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2df1df8ffbc22c818c2ffd6af8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbd9d981fd6608f76099c162a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52d89390506ed998a56a73c04c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_934b1fb8522f51ab5b85da5d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c210d0e51865d0a90546373db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ce12a460128d0abb45de6d9cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_033a1fdb4f9af609010a4a3ba9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fefceb5358f13649852bcddee4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_656ab973b96252a340fca6dc33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a358c00ae08bdea24880372d7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a85d553dbb4006bd350ab6f88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23a4e63a095ea45c880ee03d80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f6dd1048ea0bdfe60c4a3300d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90c78d3c32a3346772edf34e73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a390dc6ab65942f1ab577b7b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c97e41edad2dd3e2c225f458a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_019da5caef36b1a1af22063905"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0410389b8d9e26a76bc4df7050"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bab6cf3a1e33e6790e9b9bd7d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16a84aef47c794ac3d01f39830"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27fcf8353977273f67a62a4172"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dfa62b35548ea1e0b7e4675b2"`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ALTER COLUMN "view_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "rating" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refunds" ALTER COLUMN "requested_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "UQ_f5eea852caade6015a86c6cc82a"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "notification_prefs" SET DEFAULT '{"nearbyEvents": true, "specialOffers": true, "eventReminders": true, "reelsAndCommunity": true}'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "roles" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "roles" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "latitude" TYPE numeric(10,8)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bio" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_picture_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_picture_url" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" ALTER COLUMN "verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_logo_url"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_logo_url" text`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_website"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_website" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_description"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_description" text`);
        await queryRunner.query(`ALTER TABLE "organizers" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD "company_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "approval_method" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "featured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_by_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "approval_status"`);
        await queryRunner.query(`DROP TYPE "public"."events_approval_status_enum"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "approval_status" character varying(20) DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "booking_date" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "ticket_code" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP CONSTRAINT "UQ_3c8ed28a882f2b9a5caef4038b4"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "booking_reference"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "booking_reference" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "event_bookings_booking_reference_key" UNIQUE ("booking_reference")`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "payment_method" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "payment_status"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "payment_status" character varying(50) DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "event_bookings" DROP COLUMN "booking_status"`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD "booking_status" character varying(50) DEFAULT 'confirmed'`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "total_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ALTER COLUMN "total_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_categories" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "event_categories" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "flag_reason"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "moderation_status"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "caption"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "media_url"`);
        await queryRunner.query(`ALTER TABLE "shorts" DROP COLUMN "uploader_user_id"`);
        await queryRunner.query(`ALTER TABLE "event_reviews" DROP COLUMN "text"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "push_token"`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "status" character varying(50) DEFAULT 'published'`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "tags" text array`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "category" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "duration_seconds" integer`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "video_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "title" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD "creator_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "helpful_count" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "review_text" text`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD "review_title" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event_announcements" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "event_reviews_user_id_event_id_key" UNIQUE ("user_id", "event_id")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_follows_user_organizer" UNIQUE ("user_id", "organizer_id")`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "UQ_favorites_user_event" UNIQUE ("user_id", "event_id")`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "UQ_waitlist_entries_user_ticket_type" UNIQUE ("ticket_type_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "event_reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "CHK_events_end_date_after_start" CHECK (((event_end_date IS NULL) OR (event_end_date >= event_date)))`);
        await queryRunner.query(`CREATE INDEX "idx_shorts_event_id" ON "shorts" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shorts_creator_id" ON "shorts" ("creator_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shorts_status" ON "shorts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_reviews_event" ON "event_reviews" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "idx_event_reviews_event_id" ON "event_reviews" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "idx_event_reviews_user_id" ON "event_reviews" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_announcements_event_created" ON "event_announcements" ("created_at", "event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_schedule_items_event" ON "event_schedule_items" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_messages_event_created" ON "chat_messages" ("created_at", "event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_follows_organizer" ON "follows" ("organizer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_follows_user_created" ON "follows" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_favorites_user_created" ON "favorites" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_verification_otps_email" ON "email_verification_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_password_reset_otps_email" ON "password_reset_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_jobs_user_status" ON "notification_jobs" ("status", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_organizer_status" ON "payouts" ("organizer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_event_id" ON "payouts" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_actor_created" ON "audit_logs" ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_target" ON "audit_logs" ("target_id", "target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_waitlist_entries_tt_status_created" ON "waitlist_entries" ("created_at", "status", "ticket_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_refunds_status" ON "refunds" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_refunds_enrollment_id" ON "refunds" ("enrollment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_enrollment_id" ON "payments" ("enrollment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payments_gateway_event_id" ON "payments" ("gateway_event_id") WHERE (gateway_event_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_organizers_user_id" ON "organizers" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_events_title" ON "events" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_events_category_id_event_date" ON "events" ("category_id", "event_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_events_approval_status_deleted_at" ON "events" ("approval_status", "deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_events_event_date_start_time" ON "events" ("event_date", "start_time") `);
        await queryRunner.query(`CREATE INDEX "idx_events_date" ON "events" ("event_date") `);
        await queryRunner.query(`CREATE INDEX "idx_events_featured" ON "events" ("featured") `);
        await queryRunner.query(`CREATE INDEX "idx_events_status" ON "events" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_events_category_id" ON "events" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_events_organizer_id" ON "events" ("organizer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_media_event_id" ON "event_media" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_bookings_payout_id" ON "event_bookings" ("payout_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_event_bookings_ticket_code" ON "event_bookings" ("ticket_code") WHERE (ticket_code IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_event_bookings_reference" ON "event_bookings" ("booking_reference") `);
        await queryRunner.query(`CREATE INDEX "idx_event_bookings_status" ON "event_bookings" ("booking_status") `);
        await queryRunner.query(`CREATE INDEX "idx_event_bookings_event_id" ON "event_bookings" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "idx_event_bookings_user_id" ON "event_bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ticket_types_event_id" ON "ticket_types" ("event_id") `);
        await queryRunner.query(`ALTER TABLE "user_interests" ADD CONSTRAINT "FK_user_interests_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_interests" ADD CONSTRAINT "FK_user_interests_category" FOREIGN KEY ("category_id") REFERENCES "event_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD CONSTRAINT "shorts_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shorts" ADD CONSTRAINT "shorts_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "event_reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_reviews" ADD CONSTRAINT "event_reviews_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_announcements" ADD CONSTRAINT "FK_event_announcements_user" FOREIGN KEY ("posted_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_announcements" ADD CONSTRAINT "FK_event_announcements_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_schedule_items" ADD CONSTRAINT "FK_event_schedule_items_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_follows_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_follows_organizer" FOREIGN KEY ("organizer_id") REFERENCES "organizers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_organizer" FOREIGN KEY ("organizer_id") REFERENCES "organizers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_waitlist_entries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_waitlist_entries_ticket_type" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_waitlist_entries_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_refunds_enrollment" FOREIGN KEY ("enrollment_id") REFERENCES "event_bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_commissions_payment" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_enrollment" FOREIGN KEY ("enrollment_id") REFERENCES "event_bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizers" ADD CONSTRAINT "organizers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "fk_events_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "fk_events_rejected_by" FOREIGN KEY ("rejected_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "fk_events_approved_by" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "events_organizer_id_fkey" FOREIGN KEY ("organizer_id") REFERENCES "organizers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "events_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "event_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_event_media_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "event_bookings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "event_bookings_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "FK_event_bookings_ticket_type" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_bookings" ADD CONSTRAINT "FK_event_bookings_payout" FOREIGN KEY ("payout_id") REFERENCES "payouts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ADD CONSTRAINT "FK_ticket_types_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
